name: Auto Labeler

# pull request時に特定の文字列から始まるブランチ名だったら、labelを自動的に付与する
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto_label:
    runs-on: ubuntu-latest

    steps:
    - name: Label PRs based on branch
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const pr = context.payload.pull_request;
          const branchName = pr.head.ref;
          const labels = new Set();

          if (branchName.startsWith("rc-")) {
            labels.add("raycasting");
          } else if (branchName.startsWith("map-")) {
            labels.add("map");
          }

          if (labels.size > 0) {
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: Array.from(labels)
            });
          }